travis:
  secure:
    BINSTAR_TOKEN: D0ucdfwQT7dKTldPca9TKKPod8/T4gCSCWVJYXqt0nkSVzg4B7E9xrAkrrIDMXP43FB6teBadF/ctwSkvEdvmZmFcnX4yeYQAIGY6ElzKpVKa5iSpr4oxxc8pzxGf54TQSul7+07gtlPAql5ZboW/7XduoIoYVe2ouNS1C6o/+kgV7YOnvvvkTfDtSlnancwYwyGydodiVOjB8hSto9BaSx99ZcMDieBCYADMX5QOH5W0rT2cR0TazEzCq46I+KPnHZ03VUW8EtqmuzkLhAmrbb5GEEPeP8KXNNp8cs2vgu/0qY7REt5Z5ZmyXk+SRPk7UQyWLCmF4JX5KLWCoB3qlYJw1A+Yx3E24Cr8M9X1xarw4LPdn4WooKDBRAzlH0F1HcIqTUAu2Z4zOhDe4y+mZRao02GnXdvEqGKFVgq/3iFLeEE4PCLj+g96+aqDljl9Rvw3/NHNvH+GZ2WTRDxP4QpAtgf7rEXtGOghJUMe2ISPFyG8clNk6H/pwaov2e2Vcc5qgIKp3JPDGnqVtNLWzdyTUnXmkfaU3DSTiinG58dDqhGJfCEE06oY68PnJHwHQmDQ93FIrdcAll611MIYKrdsqGEtA0+qXqHYKBvI3XuYeZQPDAS1XOpGGFPdv1q0pVMfcJkQqE4g5WhK7+nNlOCn+592YSB933In/2v9Ow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
